import { db } from '@/db';
import { applications } from '@/db/schema';
import { randomUUID } from 'crypto';

async function main() {
    const baseDate = new Date('2024-01-20');
    
    const sampleApplications = [
        {
            submissionId: randomUUID(),
            fullName: 'Aziza Karimova',
            phone: '+998901234567',
            desiredPosition: 'Marketing Manager',
            language: 'uz',
            pageUrl: 'https://horizonwork.uz/vacancies/marketing',
            utmSource: 'telegram',
            utmCampaign: 'summer2024',
            status: 'new',
            honeypot: null,
            ipAddress: '203.0.113.10',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            submittedAt: new Date(baseDate.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(baseDate.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            submissionId: randomUUID(),
            fullName: 'Dmitry Volkov',
            phone: '+998971234568',
            desiredPosition: 'Frontend Developer',
            language: 'ru',
            pageUrl: 'https://horizonwork.uz/careers/tech',
            utmSource: 'google',
            utmCampaign: 'tech_hiring',
            status: 'processed',
            honeypot: null,
            ipAddress: '198.51.100.25',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            submittedAt: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            submissionId: randomUUID(),
            fullName: 'Sarah Johnson',
            phone: '+998931234569',
            desiredPosition: 'HR Specialist',
            language: 'en',
            pageUrl: 'https://horizonwork.uz/jobs/hr',
            utmSource: 'linkedin',
            utmCampaign: 'international',
            status: 'new',
            honeypot: null,
            ipAddress: '192.0.2.50',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
            submittedAt: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            submissionId: randomUUID(),
            fullName: 'Jamshid Rahimov',
            phone: '+998901234570',
            desiredPosition: null,
            language: 'uz',
            pageUrl: 'https://horizonwork.uz/',
            utmSource: null,
            utmCampaign: null,
            status: 'new',
            honeypot: null,
            ipAddress: '203.0.113.45',
            userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
            submittedAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            submissionId: randomUUID(),
            fullName: 'Elena Sokolova',
            phone: '+998971234571',
            desiredPosition: 'Accountant',
            language: 'ru',
            pageUrl: 'https://horizonwork.uz/finance',
            utmSource: 'instagram',
            utmCampaign: 'spring2024',
            status: 'processed',
            honeypot: null,
            ipAddress: '198.51.100.78',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1',
            submittedAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            submissionId: randomUUID(),
            fullName: 'Michael Chen',
            phone: '+998931234572',
            desiredPosition: 'Product Manager',
            language: 'en',
            pageUrl: 'https://horizonwork.uz/careers/product',
            utmSource: 'google',
            utmCampaign: 'pm_roles',
            status: 'new',
            honeypot: null,
            ipAddress: '192.0.2.120',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15',
            submittedAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            submissionId: randomUUID(),
            fullName: 'Nodira Yusupova',
            phone: '+998901234573',
            desiredPosition: 'Sales Representative',
            language: 'uz',
            pageUrl: 'https://horizonwork.uz/sales',
            utmSource: 'facebook',
            utmCampaign: 'sales_team',
            status: 'new',
            honeypot: null,
            ipAddress: '203.0.113.89',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
            submittedAt: new Date(baseDate.getTime() - 12 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(baseDate.getTime() - 12 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 12 * 60 * 60 * 1000).toISOString(),
        },
        {
            submissionId: randomUUID(),
            fullName: 'Alexey Petrov',
            phone: '+998971234574',
            desiredPosition: 'Backend Developer',
            language: 'ru',
            pageUrl: 'https://horizonwork.uz/careers/tech',
            utmSource: 'google',
            utmCampaign: 'tech_hiring',
            status: 'processed',
            honeypot: null,
            ipAddress: '198.51.100.150',
            userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            submittedAt: baseDate.toISOString(),
            createdAt: baseDate.toISOString(),
            updatedAt: baseDate.toISOString(),
        },
    ];

    await db.insert(applications).values(sampleApplications);
    
    console.log('✅ Applications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});